### PR TITLE
Fix asm-derive feature

### PR DESCRIPTION
**Pull request by ly0va**
Workaround for https://github.com/rust-lang/rust/issues/104925

### CODE REVIEW

**Comment by shamatar** [comment]
Why random ID? We have a modulus that completely specifies a field, and while we can get collisions over those, it's unlikely. 

In any case it's a temporary solution until fix is accepted in Rust compiler, so just use a string formatted modulus value there.

**Review by shamatar — CHANGES_REQUESTED** [review]
(In comments)

**Comment by shamatar** [comment]
PR for reference https://github.com/rust-lang/rust/pull/105023

**Comment by ly0va** [comment]
@shamatar as you said, it's a temporary fix anyway, so does it matter how we do it? The solution in the PR protects against the case where we use 2 equal moduli - your solution wouldn't work here. If we're implementing a kludge, we should at least make sure it's a working kludge.

**Comment by shamatar** [comment]
Even though I agree with you about protection, I'd prefer not to have randomness (and two same moduli is edge case of edge case). 

If there no other option for deterministic uniqueness, then let's accept and move forward for now

**Comment by shamatar** [comment]
Please bump a minor version in Cargo.toml for both derive and ff, so we can publish it

**Pull request merged**
